{{ if .Values.dnsConfig.enabled }}
apiVersion: tailscale.com/v1alpha1
kind: DNSConfig
metadata:
  name: dnsconfig
  namespace: {{ .Release.Namespace }}
spec:
  domain: {{ .Values.dnsConfig.domain | quote }}
  nameserver:
    image:
      repo: {{ .Values.dnsConfig.image.repo | quote }}
      tag: {{ .Values.dnsConfig.image.tag | default .Chart.AppVersion }}
{{ end }}
