apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dnsrecords-watcher-binding
subjects:
  - kind: ServiceAccount
    name: nameserver
    namespace: tailscale 
roleRef:
  kind: Role
  name: dnsrecords-watcher
  apiGroup: rbac.authorization.k8s.io
