apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dnsrecords-watcher
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["dnsrecords"]
    verbs: ["get", "list", "watch"]
